# Generated by Django 3.0.3 on 2020-03-06 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_product_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
    ]
